In [1]:
import numpy
numpy.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
import torch
torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
import numpy as np
np.random.rand(10, 10)

array([[0.17152534, 0.68562632, 0.33959898, 0.4285364 , 0.30503047,
        0.33769866, 0.81292083, 0.17287577, 0.59292308, 0.85856794],
       [0.2847042 , 0.4317122 , 0.69620427, 0.81294866, 0.56829387,
        0.56952469, 0.29512487, 0.08307179, 0.1388487 , 0.06763091],
       [0.28871422, 0.85425915, 0.99336098, 0.36984846, 0.46162034,
        0.18306197, 0.07557242, 0.32659803, 0.89394647, 0.74900993],
       [0.30605834, 0.44714644, 0.14631464, 0.51676954, 0.36579012,
        0.38328335, 0.15443397, 0.48344523, 0.21090681, 0.02160049],
       [0.94209562, 0.43216393, 0.00561966, 0.56738118, 0.53817859,
        0.8732184 , 0.5391824 , 0.12540264, 0.72100619, 0.17338015],
       [0.35451763, 0.25198994, 0.32276357, 0.07668262, 0.82651573,
        0.80978864, 0.47928335, 0.29943528, 0.48145954, 0.99953244],
       [0.73079948, 0.65020403, 0.58975158, 0.40526307, 0.2383927 ,
        0.27806173, 0.82719753, 0.34675378, 0.30423828, 0.72678876],
       [0.67666913, 0.12466541, 0.6206289